name: Update description

on:
  push:
    paths:
      - docs/description.yml
    branches:
      - ytdlp
  workflow_dispatch:
    inputs:

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install js-yaml module
      run: npm init -y && npm i js-yaml
    - name: Update description and homepage
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GH_PAT }}
        script: |
          const fs = require("fs");
          const yaml = require("js-yaml");
          const doc = yaml.load(fs.readFileSync('docs/description.yml', 'utf8'));
          // don't pass doc object as-is to prevent attacks via PRs
          const {owner, repo} = context.repo;
          if (owner !== "ytdl-patched") throw new Error(`wwner doesn't match: ${owner}`);
          if (repo  !== "ytdl-patched") throw new Error(`repo doesn't match: ${repo}`);
          if (typeof doc.description !== "string") throw new Error(`.description has wrong type: ${typeof doc.description}`);
          if (typeof doc.homepage !== "string") throw new Error(`.homepage has wrong type: ${typeof doc.homepage}`);
          github.repos.update({
            owner: "ytdl-patched",
            repo: "ytdl-patched",
            description: doc.description,
            homepage: doc.homepage,
          });
